TRAINING_LOG_KWARGS:
  logging_steps: 5
  per_device_eval_batch_size: 1
  report_to: wandb
  eval_strategy: steps
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 1
  save_strategy: steps
  save_steps: 120
  #max_steps: 1