program: mcxr_train_sweep.py # Replace with the name of your Python training script
method: bayes # Choose your search strategy: random, grid, or bayes
metric:
  name: eval_loss
  goal: minimize # Whether to minimize or maximize this metric


parameters:
  num_train_epochs:
    values: [3, 5, 7] # Discrete values to try for epochs

  warmup_ratio:
    min: 0.0 # Minimum value
    max: 0.1 # Maximum value
    distribution: uniform 

  eval_steps:
    values: [20, 50, 100] # Discrete steps for evaluation

  lr_scheduler_type:
    values: ["linear", "cosine"] 

  optim:
    values: ["adamw_8bit", "adamw_bnb_8bit", "paged_adamw_8bit", "galore_adamw_8bit"] 

  learning_rate:
    min: 0.00001 # 1e-5
    max: 0.001 # 1e-3
    distribution: log_uniform_values 

  weight_decay:
    min: 0.0001 # 1e-4
    max: 0.1 # 1e-1
    distribution: log_uniform_values 