program: train_sweep.py 
method: bayes # random, grid, or bayes
metric:
  name: eval_loss
  goal: minimize 


parameters:
  num_train_epochs:
    values: [3, 5, 7] 

  warmup_ratio:
    min: 0.0 
    max: 0.1 
    distribution: uniform 

  eval_steps:
    values: [20, 50, 100] 

  lr_scheduler_type:
    values: ["linear", "cosine"] 

  optim:
    values: ["adamw_8bit", "adamw_bnb_8bit", "paged_adamw_8bit", "galore_adamw_8bit"] 

  learning_rate:
    min: 0.00001 # 1e-5
    max: 0.001 # 1e-3
    distribution: log_uniform_values 

  weight_decay:
    min: 0.0001 # 1e-4
    max: 0.1 # 1e-1
    distribution: log_uniform_values 