VLLM_KWARGS:
  gpu_memory_utilization: 0.9
  max_model_len: MAX_SEQ_LENGTH
  #max_num_seqs: 64
  max_lora_rank: 64

SAMPLING_KWARGS:
  temperature: 0.5 #0.5
  #top_p: 0.95
  #top_k: 64
  min_p: 0.1
  stop:
    - "}"
  include_stop_str_in_output: true
  seed: 42
  max_tokens: 4096 # 2048

LANG_CODES:
  eng_Latn: English
  fra_Latn: French
  deu_Latn: German
  spa_Latn: Spanish
  por_Latn: Portuguese
  pol_Latn: Polish
  dan_Latn: Danish
  ita_Latn: Italian
  swe_Latn: Swedish
  nob_Latn: Norwegian